#!/bin/sh
if [ -e sign.c -a -e squash.awk ];then
gcc -osign sign.c
./sign < /usr/share/dict/words | sort | awk -f squash.awk > out
awk '{print NF " " $0}' < out | sort -n | tail
else
	echo "Needed files missing"
fi
